#
# 3. In the above access_switch.j2 template use a Jinja2 for loop to create all
#  of the interfaces from FastEthernet 0/1 to FastEthernet 0/24.
#  Each of the interfaces should have the following configuration:
#
# >>>>
# interface FastEthernet 0/X                    # where X is the interface number
#  switchport access vlan {{item.access_vlan}}
#  switchport mode access
#  spanning-tree portfast
# >>>>
#
# For reference on the for loop syntax see the Jinja2 documentation or look at my solution on GitHub.
#
# OUTPUT from playbook run
#(pynet) chudgins-ltm1$ ansible-playbook site.yml
# [WARNING]: Host file not found: /etc/ansible/hosts
#
# [WARNING]: provided hosts list is empty, only localhost is available
#
#
#PLAY [Generate configuration file] *********************************************
#
#TASK [Gathering Facts] *********************************************************
#ok: [localhost]
#
#TASK [access_switch : Generate configuration files] ****************************
#changed: [localhost] => (item={u'access_vlan': 101, u'snmp_community': u'applesause', u'default_gateway': u'1.1.1.1', u'hostname': u'pnet-rtr1', u'secret': u'foobar', u'ip_addr': u'1.1.1.2'})
#changed: [localhost] => (item={u'access_vlan': 101, u'snmp_community': u'applesause', u'default_gateway': u'1.1.2.1', u'hostname': u'pnet-rtr2', u'secret': u'foobar', u'ip_addr': u'1.1.2.2'})
#changed: [localhost] => (item={u'access_vlan': 101, u'snmp_community': u'applesause', u'default_gateway': u'1.1.3.1', u'hostname': u'pnet-rtr3', u'secret': u'foobar', u'ip_addr': u'1.1.3.2'})
#changed: [localhost] => (item={u'access_vlan': 101, u'snmp_community': u'applesause', u'default_gateway': u'1.1.4.1', u'hostname': u'pnet-rtr4', u'secret': u'foobar', u'ip_addr': u'1.1.4.2'})
#changed: [localhost] => (item={u'access_vlan': 101, u'snmp_community': u'applesause', u'default_gateway': u'1.1.5.1', u'hostname': u'pnet-rtr5', u'secret': u'foobar', u'ip_addr': u'1.1.5.2'})
#
#PLAY RECAP *********************************************************************
#localhost                  : ok=2    changed=1    unreachable=0    failed=0

- name: Generate configuration file
  hosts: localhost

  roles:
    - access_switch
