#
# 1. Create an Ansible playbook that generates five switch configurations based upon the below partial switch
#  configuration. The hostname, ip_addr, and default_gateway should be unique for each switch.
#
# OUTPUT from playbook run
#(pynet) chudgins-ltm1$ ansible-playbook site.yml
# [WARNING]: Host file not found: /etc/ansible/hosts
#
# [WARNING]: provided hosts list is empty, only localhost is available
#
#
#PLAY [Generate configuration file] *********************************************
#
#TASK [Gathering Facts] *********************************************************
#ok: [localhost]
#
#TASK [access_switch : Generate configuration files] ****************************
#changed: [localhost] => (item={u'access_vlan': 101, u'snmp_community': u'netwon', u'default_gateway': u'1.1.1.1', u'hostname': u'pnet-rtr1', u'secret': u'foobar', u'ip_addr': u'1.1.1.1'})
#changed: [localhost] => (item={u'access_vlan': 101, u'snmp_community': u'netwon', u'default_gateway': u'1.1.2.1', u'hostname': u'pnet-rtr2', u'secret': u'foobar', u'ip_addr': u'1.1.2.2'})
#changed: [localhost] => (item={u'access_vlan': 101, u'snmp_community': u'netwon', u'default_gateway': u'1.1.3.1', u'hostname': u'pnet-rtr3', u'secret': u'foobar', u'ip_addr': u'1.1.3.2'})
#changed: [localhost] => (item={u'access_vlan': 101, u'snmp_community': u'netwon', u'default_gateway': u'1.1.4.1', u'hostname': u'pnet-rtr4', u'secret': u'foobar', u'ip_addr': u'1.1.4.2'})
#changed: [localhost] => (item={u'access_vlan': 101, u'snmp_community': u'netwon', u'default_gateway': u'1.1.5.1', u'hostname': u'pnet-rtr5', u'secret': u'foobar', u'ip_addr': u'1.1.5.2'})
#
#PLAY RECAP *********************************************************************
#localhost                  : ok=2    changed=1    unreachable=0    failed=0
#

- name: Generate configuration file
  hosts: localhost

  roles:
    - access_switch