---
# 1. For the VLAN IDs randomly pick three numbers between 100 and 999.

- name: Class6 Exercise1
  hosts: arista

  tasks:
    - name: create VLANs
      eos_vlan: name={{ item.vlan_name }} vlanid={{ item.vlan_id }}
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
        - {vlan_name: red, vlan_id: 809}
        - {vlan_name: white, vlan_id: 811}
        - {vlan_name: black, vlan_id: 821}