---
#2. Use Ansible to configure your 'primary Ethernet interface' as follows:
#
#interface description: *** IN USE ***
#switchport mode: access
#VLAN: <one of the VLANs created in exercise1>
#
#Your 'primary Ethernet interface' is specified in your ~/ansible-hosts file.
#
#If your primary interface is already 'IN USE' (by someone else), then use your secondary interface
# (once again specified in ~/ansible-hosts).  You can determine if an interface is already in use
#  by SSH'ing into the switch. Reminder, do NOT use Ethernet1.

#OUTPUT

#SWITCH

- name: Class6 Exercise2
  hosts: arista

  tasks:
    - name: Interface Ethernet7 description
      eos_interface: name=Ethernet7 description="*** IN USE ***"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: switchport access mode Interface Ethernet7 and VLAN809 assignment
      eos_switchport: name=Ethernet7 mode=access access_vlan=809
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https