---
#5. Use the cisco_file_transfer.py module to transfer a small file to the Cisco pynet-rtr1 router.
# will need
# ansible-playbook <playbook_name> --module-path ~/ANSIBLE/library/

#OUTPUT

#SWITCH

- name: Class6 Exercise5
  hosts: pynet-rtr1
  gather_facts: False

  tasks:
  - name: File transfer
    cisco_file_transfer:
      source_file=ch_file.txt
      dest_file=ch_file.txt
      overwrite=true
      enable_scp=true
      host={{ host }}
      port={{ port }}
      username={{ username }}
      password={{ password }}