#
# 2. Expand upon the above template by adding a Jinja2 if conditional.
# The if conditional should add the below SNMPv3 commands and associated ACL
# (i.e. if SNMPv3, then the below commands are added into the configuration file):
# >>>>
# access-list 98 remark *** SNMP ***
# access-list 98 permit any
# !
# snmp-server view VIEWSTD iso included
# snmp-server group READONLY v3 priv read VIEWSTD access 98
# snmp-server user pysnmp READONLY v3 auth sha auth_key priv aes 128 encrypt_key
# >>>>
#
# OUTPUT from playbook run
#(pynet) chudgins-ltm1$ ansible-playbook site.yml
# [WARNING]: Host file not found: /etc/ansible/hosts
#
# [WARNING]: provided hosts list is empty, only localhost is available
#
#
#PLAY [Generate configuration file] *********************************************
#
#TASK [Gathering Facts] *********************************************************
#ok: [localhost]
#
#TASK [access_switch : Generate configuration files] ****************************
#changed: [localhost] => (item={u'access_vlan': 101, u'snmp_community': u'applesause', u'default_gateway': u'1.1.1.1', u'hostname': u'pnet-rtr1', u'secret': u'foobar', u'ip_addr': u'1.1.1.2', u'SNMPv3': True})
#changed: [localhost] => (item={u'access_vlan': 101, u'snmp_community': u'applesause', u'default_gateway': u'1.1.2.1', u'hostname': u'pnet-rtr2', u'secret': u'foobar', u'ip_addr': u'1.1.2.2', u'SNMPv3': False})
#changed: [localhost] => (item={u'access_vlan': 101, u'snmp_community': u'applesause', u'default_gateway': u'1.1.3.1', u'hostname': u'pnet-rtr3', u'secret': u'foobar', u'ip_addr': u'1.1.3.2', u'SNMPv3': True})
#changed: [localhost] => (item={u'access_vlan': 101, u'snmp_community': u'applesause', u'default_gateway': u'1.1.4.1', u'hostname': u'pnet-rtr4', u'secret': u'foobar', u'ip_addr': u'1.1.4.2', u'SNMPv3': False})
#changed: [localhost] => (item={u'access_vlan': 101, u'snmp_community': u'applesause', u'default_gateway': u'1.1.5.1', u'hostname': u'pnet-rtr5', u'secret': u'foobar', u'ip_addr': u'1.1.5.2', u'SNMPv3': True})
#
#PLAY RECAP *********************************************************************
#localhost                  : ok=2    changed=1    unreachable=0    failed=0


- name: Generate configuration file
  hosts: localhost

  roles:
    - access_switch